name: ci

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build
        run: docker build -t build-test .

  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Create comment
        id: create
        run: |
          python3 main.py
        env:
          INPUT_TYPE: create
          INPUT_BODY: "- [ ] Run tests"
          INPUT_ISSUE_NUMBER: "1"
          INPUT_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update comment
        id: edit
        run: |
          python3 main.py
        env:
          INPUT_TYPE: edit
          INPUT_BODY: "- [x] Run tests"
          INPUT_COMMENT_ID: "${{ steps.create.outputs.id }}"
          INPUT_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test create and edit
        env:
          CREATE_ID: ${{ steps.create.outputs.id }}
          EDIT_ID: ${{ steps.edit.outputs.id }}
          EDIT_BODY: ${{ steps.edit.outputs.body }}
        run: |
          [[ "$CREATE_ID" == "$EDIT_ID" ]] || exit 1
          [[ "$EDIT_BODY" == "- [x] Run tests" ]] || exit 1

      - name: Delete comment
        id: delete
        run: |
          python3 main.py
        env:
          INPUT_TYPE: delete
          INPUT_COMMENT_ID: "${{ steps.edit.outputs.id }}"
          INPUT_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test delete
        env:
          DELETE_ID: ${{ steps.delete.outputs.id }}
        run: |
          [[ "$DELETE_ID" == "" ]] || exit 1
